import beescriLogo from "@/assets/beescri.svg";
import { Button } from "@/components/ui/button";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { useEditor } from "@/contexts/editor-context";
import { saveAs } from "file-saver";
import JSZip from "jszip";
import { Link } from "react-router-dom";
import { toast } from "sonner";

export const Navbar = () => {
  return (
    <header className="py-2.5 px-5 border-b flex items-center justify-between">
      <Link to="/">
        <img src={beescriLogo} alt="Beescri" className="size-8" />
      </Link>
      <nav className="space-x-2">
        <ExportButton />
      </nav>
    </header>
  );
};

const ExportButton = () => {
  const { html, css, js } = useEditor();

  const handleExport = async () => {
    try {
      const zip = new JSZip();
      zip.file(
        "index.html",
        `
<!DOCTYPE html>
<html lang="en">

<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta charset="UTF-8" />
<link rel="stylesheet" href="style.css" />
<title>My Bee 🐝</title>
</head>

<body>
<!-- 🐝 Auto-generated by ${window.location.href} -->
${html}
<script src="app.js"></script>
</body>

</html>`.trim()
      );
      zip.file("style.css", css);
      zip.file("app.js", js);

      const content = await zip.generateAsync({ type: "blob" });
      saveAs(content, "bee.zip");

      toast.success("Exported successfully");
    } catch (err) {
      if (err instanceof Error) {
        toast.error(`Failed to export: ${err.message}`);
        console.error(err);
      }
    }
  };

  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger asChild>
          <Button variant="ghost" size="sm" onClick={handleExport}>
            Export
          </Button>
        </TooltipTrigger>
        <TooltipContent>
          <p>Export as zip</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
};
